[1]
endpoint_url = "${ETH_MAINNET_RPC_URL}"

[1.bool]
is_testnet = false

[1.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
uniswap_v4_pool_manager = "0x000000000004444c5dc75cB358380D2e3dE08A90"
airlock_multisig = "0x21E2ce70511e4FE542a97708e89520471DAa7A66"
airlock = "0xDe3599a2eC440B296373a983C85C365DA55d9dFA"
clone_erc20_factory = "0xe7Df2A4520C26a2D4Dedb3a7585BFBcd30eABA6e"
clone_erc20_votes_factory = "0x5A92bFfbc01ea0396A9c7D4154d36d4EAF2e483E"
no_op_governance_factory = "0xddAE8B3eD08184682f7Bc32B74d943cEEfEab638"
no_op_migrator = "0x233A71A7bB928b1357A1Ebf454298320989Ca5B5"

[11155111]
endpoint_url = "${ETH_SEPOLIA_RPC_URL}"

[11155111.bool]
is_testnet = true

[11155111.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
uniswap_v4_pool_manager = "0xE03A1074c86CFeDd5C142C4F04F1a1536e203543"
airlock_multisig = "0x0abCf819FD57C9f0141628410fFC273405E44426"
airlock = "0xDe3599a2eC440B296373a983C85C365DA55d9dFA"
clone_erc20_factory = "0xe7Df2A4520C26a2D4Dedb3a7585BFBcd30eABA6e"
clone_erc20_votes_factory = "0x5A92bFfbc01ea0396A9c7D4154d36d4EAF2e483E"
no_op_governance_factory = "0xddAE8B3eD08184682f7Bc32B74d943cEEfEab638"
no_op_migrator = "0x233A71A7bB928b1357A1Ebf454298320989Ca5B5"

[8453]
endpoint_url = "${BASE_MAINNET_RPC_URL}"

[8453.bool]
is_testnet = false

[8453.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
airlock = "0x660eAaEdEBc968f8f3694354FA8EC0b4c5Ba8D12"
token_factory_80 = "0xf0B5141dD9096254B2ca624dff26024f46087229"
uniswap_v4_pool_manager = "0x498581ff718922c3f8e6a244956af099b2652b2b"
doppler_deployer = "0xb35469ee64A87Afd19B31615094fE3962d73e421"
uniswap_v4_initializer = "0x53b4c21a6Cb61D64F636ABBfa6E8E90E6558e8ad"

[130]
endpoint_url = "${UNICHAIN_MAINNET_RPC_URL}"

[130.bool]
is_testnet = false

[130.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
airlock = "0x77ebfbae15ad200758e9e2e61597c0b07d731254"
token_factory_80 = "0xf0B5141dD9096254B2ca624dff26024f46087229"
uniswap_v4_pool_manager = "0x1f98400000000000000000000000000000000004"

[143]
endpoint_url = "${MONAD_MAINNET_RPC_URL}"

[143.bool]
is_testnet = false

[143.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
airlock = "0x660eaaedebc968f8f3694354fa8ec0b4c5ba8d12"
token_factory_80 = "0xf0B5141dD9096254B2ca624dff26024f46087229"
uniswap_v4_pool_manager = "0x188d586ddcf52439676ca21a244753fa19f9ea8e"
doppler_deployer = "0xb35469ee64A87Afd19B31615094fE3962d73e421"
uniswap_v4_initializer = "0x53b4c21a6Cb61D64F636ABBfa6E8E90E6558e8ad"

[4326]
endpoint_url = "${MEGAETH_MAINNET_RPC_URL}"

[4326.bool]
is_testnet = false

[4326.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
airlock_multisig = "0x21E2ce70511e4FE542a97708e89520471DAa7A66"
airlock = "0xDe3599a2eC440B296373a983C85C365DA55d9dFA"
no_op_migrator = "0x233A71A7bB928b1357A1Ebf454298320989Ca5B5"
no_op_governance_factory = "0xddAE8B3eD08184682f7Bc32B74d943cEEfEab638"

[84532]
endpoint_url = "${BASE_SEPOLIA_RPC_URL}"

[84532.bool]
is_testnet = true

[84532.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
airlock = "0x3411306ce66c9469bff1535ba955503c4bde1c6e"
token_factory_80 = "0xf0B5141dD9096254B2ca624dff26024f46087229"
airlock_multisig = "0x0abCf819FD57C9f0141628410fFC273405E44426"
uniswap_v4_pool_manager = "0x05E73354cFDd6745C338b50BcFDfA3Aa6fA03408"
clone_erc20_factory = "0xbf4Ca4D527c9760A884df31292f72E9AcA503045"
clone_erc20_votes_factory = "0x9a497a9fB78e49984B9d260abA1F4AD6321D4D92"
doppler_deployer = "0xb35469ee64A87Afd19B31615094fE3962d73e421"
uniswap_v4_initializer = "0x53b4c21a6Cb61D64F636ABBfa6E8E90E6558e8ad"
uniswap_v4_scheduled_multicurve_hook = "0xc6a562cb5CbFA29BCB1bDCCF903b8B8f2E4A2DC0"
uniswap_v4_scheduled_multicurve_initializer = "0xF84378C9F39e0FF267f3101c88773359c5393876"

[1301]
endpoint_url = "${UNICHAIN_SEPOLIA_RPC_URL}"

[1301.bool]
is_testnet = true

[1301.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
airlock = "0x0d2f38d807bfad5c18e430516e10ab560d300caf"
token_factory_80 = "0xf0B5141dD9096254B2ca624dff26024f46087229"
airlock_multisig = "0x0abCf819FD57C9f0141628410fFC273405E44426"
uniswap_v4_pool_manager = "0x00b036b58a818b1bc34d502d3fe730db729e62ac"
uniswap_v4_scheduled_multicurve_hook = "0xc6a562cb5CbFA29BCB1bDCCF903b8B8f2E4A2DC0"
uniswap_v4_scheduled_multicurve_initializer = "0xF84378C9F39e0FF267f3101c88773359c5393876"

[10143]
endpoint_url = "${MONAD_TESTNET_RPC_URL}"

[10143.bool]
is_testnet = true

[10143.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
airlock = "0xDe3599a2eC440B296373a983C85C365DA55d9dFA"
token_factory_80 = "0xf0B5141dD9096254B2ca624dff26024f46087229"
airlock_multisig = "0x0abCf819FD57C9f0141628410fFC273405E44426"
uniswap_v4_pool_manager = "0xe93882f395B0b24180855c68Ab19B2d78573ceBc"
doppler_deployer = "0xb35469ee64A87Afd19B31615094fE3962d73e421"
uniswap_v4_initializer = "0x53b4c21a6Cb61D64F636ABBfa6E8E90E6558e8ad"

[6343]
endpoint_url = "${MEGAETH_TESTNET_RPC_URL}"

[6343.bool]
is_testnet = true

[6343.address]
create2_factory = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
create_x = "0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed"
airlock_multisig = "0x0abCf819FD57C9f0141628410fFC273405E44426"
airlock = "0xDe3599a2eC440B296373a983C85C365DA55d9dFA"
no_op_migrator = "0x233A71A7bB928b1357A1Ebf454298320989Ca5B5"
no_op_governance_factory = "0xddAE8B3eD08184682f7Bc32B74d943cEEfEab638"
